import Banner from '../components/common/Banner';
import Breadcrumb from '../components/common/Breadcrumb';
import LegalSideNav from '../components/common/LegalSideNav';
import '../../styles/subpage.min.css';

export const metadata = {
  title: 'Kullanıcı Sözleşmesi - Sigorka Hizmet Şartları | Sigorka',
  description: 'Sigorka\'yı kullanırken geçerli olan şartlar, hak ve yükümlülüklerin tümüne kullanıcı sözleşmesi üzerinden ulaşabilir ve detayları inceleyebilirsiniz.',
  alternates: {
    canonical: 'https://sigorka.com/kullanici-sozlesmesi'
  },
  openGraph: {
    title: 'Kullanıcı Sözleşmesi - Sigorka Hizmet Şartları | Sigorka',
    description: 'Sigorka\'yı kullanırken geçerli olan şartlar, hak ve yükümlülüklerin tümüne kullanıcı sözleşmesi üzerinden ulaşabilir ve detayları inceleyebilirsiniz.',
    url: 'https://sigorka.com/kullanici-sozlesmesi',
    type: 'website'
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Kullanıcı Sözleşmesi - Sigorka Hizmet Şartları | Sigorka',
    description: 'Sigorka\'yı kullanırken geçerli olan şartlar, hak ve yükümlülüklerin tümüne kullanıcı sözleşmesi üzerinden ulaşabilir ve detayları inceleyebilirsiniz.'
  }
};

export default function KullaniciSozlesmesiPage() {
  return (
    <>
      <Banner title1="Bilgi Merkezi" title2="Kullanıcı Sözleşmesi" size="sm" />
      <section className="page-content">
        <div className="container container--sm">
          <Breadcrumb items={[
            { name: 'Ana Sayfa', href: '/' },
            { name: 'Bilgi Merkezi', href: '#' },
            { name: 'Kullanıcı Sözleşmesi' }
          ]} />
          <div className="row pt-lg-4">
            <div className="col-lg-4 col-md-3">
              <LegalSideNav />
            </div>
            <div className="col-lg-8 col-md-9">
              <div className="text-content">
                <h4>Kullanıcı Sözleşmesi</h4>
                <p><span><strong>Kullanıcı S</strong></span><span><strong>özleşmesi</strong></span></p>
                <p><span><strong>ARMOR KATILIM-</strong></span><span><strong> … İ</strong></span><span><strong>NTERNET Sİ</strong></span><span><strong>TESİ </strong></span><span><strong>KULLANIM SÖ</strong></span><span><strong>ZLEŞ</strong></span><span><strong>MESİ</strong></span></p>
                <p><span><strong>1- Armor Katılım Sigorta ve Reasü</strong></span><span><strong>rans Brokerlığı A.Ş.</strong></span></p>
                <p><span>Armor Katılım Sigorta ve Reasü</span><span>rans Brokerlığı A.Ş., broker olarak; sigorta veya reasü</span><span>rans s</span><span>özleşmesi yaptırmak isteyen kullanıcıları temsil eden, işbu s</span><span>özleşmelerin yaptırılacağı şirketlerin seçiminde tamamen tarafsız ve bağımsız davranarak teminat almak isteyen kişilerin hak ve menfaatlerini g</span><span>özeten, sigorta s</span><span>özleşmesi yapmak isteyenlerle sigorta şirketlerini bir araya getiren ve sigorta s</span><span>özleşmelerinde aracılık eden sigorta ve reasü</span><span>rans brokerliği kuruluşudur. Armor Katılım Sigorta ve Reasü</span><span>rans Brokerlığı A.Ş, sigorta s</span><span>özleşmesinin akdinden </span><span>önceki hazırlık çalışmalarını yapmakta ve gerektiğinde bu anlaşmaların uygulanmasında veya tazminatın </span><span>ödenmesinde yardımcı olmaktadır.</span></p>
                <p><span>Şirketimiz faaliyetlerini T.C.Başbakanlık Hazine Müsteşarlığı&apos;nca verilen ruhsat altında ilgili mevzuat hükümlerine g</span><span>öre yürütmektedir.</span></p>
                <p><span><strong>2-Ön Bilgilendirme</strong></span></p>
                <p><span>Bu siteyi ziyaret eden veya bu sitede sunulan hizmetlerden yararlanmayı talep eden kullanıcı işbu </span><span>&quot;Kullanı</span><span>m S</span><span>özleşmesi</span><span>&quot;nde yer alan hüküm ve şartların tamamını kabul eder.&nbsp; Kullanıcı, … internet sitesini kullandığı veya … tarafından sunulan hizmetlerden yararlanmayı talep ettiği takdirde işbu </span><span>&quot;Kullanı</span><span>m S</span><span>özleşmesi</span><span>&quot;nde yer alan hüküm ve şartlar ile bu metnin ayrılmaz bir parçası olan </span><span>&quot;Gizlilik Politikası&quot; hükümlerini ve bu sitedeki diğer talimatlara bağlı olmayı kabul ve taahhüt etmektedir.</span></p>
                <p><span>Medeni hakları kullanmaya ehil tüm gerçek ve tüzel kişiler Şirketin sunduğu hizmetlerden yararlanabilir. 18 yaşını doldurmamış veya reşit olmayanlar, kısıtlılar ve temyiz kudretine sahip olmayanlar ancak veli veya kanuni temsilcileri vasıtasıyla işlem yapabilirler. Poliçe yaptırmanız için gerçek ad veya unvanınızı, adresinizi, telefon numaranızı ve geçerli kredi kartı bilgilerinizi sisteme girmeniz gerekmektedir. Kendi adınıza ve başkaları yararına da sigorta talebinde bulunmanız mümkündür.</span></p>
                <p><span>Armor Katılım Sigorta ve Reasü</span><span>rans Brokerlığı A.Ş</span><span>. , işbu </span><span>&quot;Kullanı</span><span>m S</span><span>özleşmesi&quot;, </span><span>&quot;Gizlilik Politikası&quot; </span><span>ve diğer talimatlara ilişkin dilediği zaman ve gerekli g</span><span>ördüğü değişiklikleri yapma hakkını saklı tutar. S</span><span>öz konusu değişiklikler işbu sitede yayı</span><span>nlandıkları tarihlerden itibaren ve Armor Katılım tarafından kullanıcıya ayrıca bildirme yükümlülüğü olmaksızın kullanıcı için geçerli ve bağ</span><span>layıcı olacaktır</span><span>. … hizmetlerinden yararlanmaya devam etmekle bu değişiklikleri de kabul etmiş sayılırsınız.</span></p>
                <p><span><strong>3-Taraflar</strong></span></p>
                <p><span>İşbu Kulanı</span><span>m S</span><span>özleşmesi (&quot;S</span><span>özleşme&quot;) … (İnternet Sitesi) internet sitesinin kullanım hakkı sahibi, Sahrayıcedit Mah. Batman Sk. No:30/42 Kadık</span><span>öy / İstanbul adresinde mukim Armor Katılım Sigorta ve Reasü</span><span>rans Brokerlığı A.Ş (Bundan b</span><span>öyle &quot;Şirket&quot; olarak anılacaktır) ile İnternet Sitesi</span><span>&apos;ni kullanan internet kullanıcısı (Bundan b</span><span>öyle &quot;Kullanıcı&quot; olarak anılacaktır) arasında akdedilmiştir.</span></p>
                <p><span><strong>4-S</strong></span><span><strong>özleşmenin Konusu</strong></span></p>
                <p><span>İşbu S</span><span>özleşme&apos;nin konusu,&nbsp; Kullanıcının, Şirket</span><span>&apos;in sahip olduğu İnternet Sitesi&apos;nden yararlanma ve kullanım koşullarının belirlenmesidir. İşbu S</span><span>özleşme, Kullanıcı&apos;nın … web/mobil sitesine ya da mobil uygulamasına giriş yapmasıyla ve/veya … web/mobil sitesine ya da mobil uygulamasın </span><span>Üye Ol adımındaki işlemlerin devam etmesini sağlayan butona tıklaması ile kurulacak olup, işbu S</span><span>özleşmenin kurulması </span><span>ile eşzamanlı olarak Kullanıcı/</span><span>Ü</span><span>ye Armor Katılım Sigorta ve Reasü</span><span>rans Brokerlığı A.Ş.</span><span>&apos;yi sigorta şirketleri nezdinde kendi adına hareket etmek üzere yetkili sigorta brokeri olarak yetkilendirmiş olacaktır. İşbu S</span><span>özleşme şirketin vereceği sigorta brokerlik hizmetine ilişkin tarafların hak ve yükümlülüklerine dair hükümleri de düzenlemektedir.</span></p>
                <p><span>5-Kullanıcının Hak Ve Yükümlülükleri</span></p>
                <p><span>5.1 Kullanıcı , İnternet Sitesi</span><span>&apos;ni kullanırken tüm yasal mevzuat hükümlerine uymayı </span><span>ve s</span><span>öz konusu hükümleri ihlal etmemeyi; aksi halde oluşacak tüm hukuki ve cezai yükümlülüklerden tamamen ve mü</span><span>nhasıran sorumlu olduğunu kabul ve taahhüt eder.</span></p>
                <p><span>5.2&nbsp; Kullanıcı, İnternet Sitesi</span><span>&apos;nde başkalarının hizmetleri kullanmasını önleyici veya zorlaştırıcı faaliyet (spam, virüs vb.) ve işlemlerde bulunamaz.</span></p>
                <p><span>5.3 Kullanıcı, İnternet Sitesi</span><span>&apos;ni hiçbir şekilde kamu düzenini bozucu, genel ahlaka aykırı, başkalarını rahatsız ve taciz edici şekilde, başkalarının fikri ve telif hakları</span><span>na tecavüz edecek şekilde ve yasalara aykırı herhangi bir amaç için kullanamaz.</span></p>
                <p><span>5.4&nbsp; Kullanıcı İnternet Sitesi</span><span>&apos;ni kullanırken&nbsp; verdiği kişisel ve diğer sair bilgilerin gerçeğe uygun olduğunu ve Şirket</span><span>&apos;in bu bilgilerin gerçeğe aykırılığı nedeniyle uğrayacağı tüm zararları defaten ve nakden tazmin edeceğini beyan ve taahhüt eder.</span></p>
                <p><span>5.5&nbsp; Şirket, Kullanıcı verilerinin yetkisiz kişilerce ele geçirilmesinden yazılım ve verilerine gelebilecek zararlardan dolayı sorumlu tutulmayacaktır. Kullanıcı, İnternet Sitesi</span><span>&apos;nin kullanılmasından dolayı uğrayabileceği herhangi bir zarar yüzü</span><span>nden Şirket</span><span>&apos;ten tazminat talep etmemeyi peşinen kabul etmiştir.</span></p>
                <p><span>5.6&nbsp; Kullanıcı, başka internet kullanıcılarının bilgilerine ve yazılımlarına izinsiz olarak ulaşmamayı veya bunları kullanmamayı kabul etmiştir. Aksi halde, bu nedenle doğacak hukuki ve cezai sorumluluk tamamen kullanıcıya aittir.</span></p>
                <p><span>5.7 Şirket web sitesinin virüs ve benzeri amaçlı yazılımlardan arındırılmış olması için mevcut imkanlar dahilinde tedbir alınmıştır. Bunun yanında nihai güvenliğin sağlanması için kullanıcının, kendi virüs koruma sistemini tedarik etmesi ve gerekli korunmayı sağlaması gerekmektedir. Bu bağlamda , İnternet Sitesi</span><span>&apos;ne girmesiyle, kendi yazılım ve işletim sistemlerinde oluşabilecek tüm hata ve bunları</span><span>n doğrudan ya da dolaylı sonuçlarından kendisinin sorumlu olduğunu kabul etmiş sayılır.</span></p>
                <p><span>5.8 Kullanıcıya verilen hesap adı/numarası </span><span>ve şifre kullanılarak yapılan tüm işlemlerin sorumluluğu kullanıcının şahsına aittir. Bu nedenle kullanıcı s</span><span>öz konusu hesap adını/numarasını </span><span>ve şifresini güvenli bir şekilde saklama ve üçüncü kişilerle paylaşmama yükümlülüğü olduğunu, gerektiğinde hesap adı/numarası </span><span>ve şifresinin değiştirilmesini Şirketten isteyeceğini, aksi taktirde doğacak zararlardan Şirketin hiçbir sorumluluğu bulunmayacağını kabul ve taahhüt eder.</span></p>
                <p><span>5.9 Kullanıcı haksız menfaat elde etmek iç</span><span>in doğru olmayan beyanlarda bulunmayacağını, mevcut hasarları gizlemek&nbsp; sureti ile çı</span><span>kar sağlamaya çalışmayacağını, sahte isim ve kredi kartları kullanmak gibi cezai sorumluluklar doğuracak eylemlerde bulunmayacağını kabul,, beyan ve taahhüt eder. Bu gibi durumlarda Şirket her zaman tek taraflı olarak herhangi bir sorumluluğu doğmaksızın kullanıcının/üyenin üyeliğini askıya alma sonlandırma ve kullanıcıya ait tüm veri belge ve dosyaları silme, sitelere girişi yasaklama, şikayette bulunma v.b. gibi uygun g</span><span>ö</span><span>receği tedbirleri almaya yetkilidir.</span></p>
                <p><span>5.10 Şirket web sitesini ve mobil sitesini kullanarak sunulan içeriği ve çeşitli hizmetleri kullanan kullanıcı </span><span>ve üyeler yalnızca hukuka uygun, şahsi veya kurumsal amaçlarla site üzerinden işlem yapabilirler. Kullanıcıların site üzerinden yaptığı işlemlerde hukuki ve cezai sorumluluk kendilerine aittir.</span></p>
                <p><span>Kullanıcı, şirketin ve/veya başka bir üçüncü şahsın hakları</span><span>na tecavüz teşkil edecek nitelikteki herhangi bir iş ve eylemde bulunmayacağını, yazılı, g</span><span>örsel ve işitsel bilgileri açıklamayacağını, açıkladığı taktirde bu yazılı, g</span><span>örsel ve işitsel bilginin Şirket tarafından kullanılması, işlenmesi, saklanması, açıklanması </span><span>ve üçüncü kişilere kişilerle paylaşılması halinde Şirketin hiçbir hukuki ve cezai sorumluluğu doğmayacağını kabul ve taahhüt eder.</span></p>
                <p><span>6-Şirketin Hak ve Yükümlülükleri</span></p>
                <p><span>6.1 Şirket tarafından İnternet Sitesi</span><span>&apos;nin iyileştirilmesine, geliştirilmesine y</span><span>önelik olarak ve/veya yasal mevzuat çerçevesinde siteye erişmek için kullanılan Internet servis sağ</span><span>layıcısını</span><span>n adı ve Internet Protokol (IP) adresi, Siteye erişilen tarih ve saat, sitede bulunulan sırada erişilen sayfalar ve siteye doğrudan bağlanılmasını sağlayan Web sitesinin Internet adresi gibi birtakım bilgiler toplanabilir, işlenebilir, hukuka uygun amaçlarla kullanılabilir.</span></p>
                <p><span>6.2&nbsp; Şirket, sitenin içeriğini, tasarımını ve yazılımını dilediği zaman değiştirme, kullanıcılara sağlanan herhangi bir hizmeti değiştirme, durdurma ya da sonlandırma ve dilediği zaman internet sitesinde kayıtlı olan kullanıcı bilgi ve verilerini silme hakkına haizdir.</span></p>
                <p><span>6.3 Şirket, işbu S</span><span>özleşme&apos;nin koşullarını hiçbir şekil ve surette </span><span>ön ihbara ve/veya ihtara gerek kalmaksızın her zaman güncelleyebilir, değiştirebilir veya yürürlükten kaldırabilir. Güncellenen, değiştirilen ya da yürürlükten kaldırılan her hüküm, yayın tarihinde tüm kullanıcılar iç</span><span>in hüküm ifade edecektir.</span></p>
                <p><span>6.4 Şirketin sorumluluğu, sitede belirtilen, vermeyi kabul ettiği, sigorta s</span><span>özleşmesinin yapılmasına y</span><span>önelik hizmetlerin sağlanması ve gerektiğinde hasar bedellerinin </span><span>ödenmesine yardımcı olunmasıyla sınırlıdır. Sigorta poliçesinden doğan hak ve sorumluluklar s</span><span>öz konusu s</span><span>özleşmenin taraflarına ait olup, bunların ifasında Şirketin hiç bir sorumluluğu yoktur.</span></p>
                <p><span>Poliçe şartlarında, fiyatlarda yapılacak değişiklikler, hasar </span><span>ödemeleri ve poliçenin uygulanmasına ilişkin her türlü konu Sigorta Şirketlerinin tâbii olduğu kanun ve y</span><span>önetmelikler çerçevesinde ilgili Sigorta Şirketinin uhdesinde ve sorumluluğ</span><span>undadır.</span></p>
                <p><span>6.5 Şirket Kullanıcı tarafından kendisine iletilen veya Site veya Mobil Site üzerinden kendileri tarafından yüklenen, değiştirilen veya sağlanan bilgi ve içeriklerin doğruluğunu araştırma, bu bilgi ve içeriklerin güvenli, doğru ve hukuka uygun olduğunu taahhüt ve garanti etmekle yükümlü veya sorumlu değildir.</span></p>
                <p><span>Şirket, s</span><span>öz konusu bilgi ve içeriklerin yanlış veya hatalı olmasından dolayı ortaya çıkacak hiçbir zarardan da sorumlu tutulamaz.</span></p>
                <p><span>6.6 Şirketten hizmet alınmış olması Şirket tarafından, sigorta şirketinin veya sigorta ettirenin/sigortalının ediminin garanti edildiği anlamına gelmez. Bu nedenle sigorta poliçesindeki borçlardan dolayı Şirketin hiç bir sorumluluğu bulunmamaktadır. Sigorta teminatı ancak sigorta şirketleri tarafından verilmektedir. Şirket, sigorta teminatı vermemekte sadece sigorta şirketleri ile sigorta ettiren/sigortalı arasında anlaşma yapılmasına aracılık yapmaktadır.</span></p>
                <p><span>6.7 Poliçe prim tahsilat sayfasında istenen kredi kartı bilgileri, siteden alışveriş yapan müşterilerin güvenliğini en üst seviyede tutmak amacıyla hiçbir şekilde Şirket sunucularında tutulmamaktadır. Bu şekilde </span><span>ödemeye y</span><span>önelik tüm işlemlerin … web/mobil sitesine ya da mobil uygulaması ara yüzü üzerinden sigorta şirketi, banka ve kullanıcı bilgisayarı arasında gerçekleşmesi sağlanmaktadır.</span></p>
                <p><span>6.8 Poliçe şartları, teminatlar, prim oran ve miktarları ile ilgili olarak sitemizde yer alan tüm bilgiler sigorta şirketlerinden alınmış bilgilerdir. Sigorta şirketlerinin bu şartları değiştirmeleri halinde Şirketten bu konuda bir talepte bulunulamaz. Şirket, sigorta şirketlerinin bu sitede yer alan şartlarla poliçe temin edeceğini de garanti etmez. Geçerli poliçe şartları düzenlenecek poliçede yer alan şartlar olacaktır.</span></p>
                <p><span>6.9 Şirketin web / mobil sitesi veya web / mobil sitesinde bulunan </span><span>&quot;</span><span>&quot;link&quot;ler Şirketin diğer kişi ve kuruluşlarla bir hukuki ilişki içerisinde olduğu veya bu kişi ve kuruluşların edimlerini, güvenilirliklerini taahhüt ettiği, onlar adına hareket ettiği veya onlara herhangi bir konuda yetki verdiği ya da bunların eylem ve işlemlerinden sorumlu olduğu anlamına gelmez. Doğrudan Şirket tarafından taahhüt edilmeyen hiç bir edim Şirket için bağ</span><span>layıcı değildir.</span></p>
                <p><span>6.10 Bu internet sitesinde ve mobil sitede yer alan her türlü bilgi ve belge Şirket tarafından sadece bilgilendirmek amacı ile sunulmakta olup, doğrulukları ve içerikleri Şirket tarafından garanti edilmemektedir. Bu nedenle işbu bilgi ve belgelere dayanılarak yapılan işlemlerden dolayı doğacak doğrudan ve/veya dolaylı </span><span>her türlü maddi, manevi zararlar ve masraflardan, üçüncü kişilerin uğrayabilecekleri zararlardan dolayı Şirket sorumlu tutulamaz.</span></p>
                <p><span>6.11 Bu internet sitesinin ve mobil sitesi kullanımı sırasında herhangi bir arıza, hata, eksiklik, kesinti, nakilde gecikme, bilgisayar virüsü, hat veya sistem arızası ya da mücbir sebepler sonucu doğrudan veya dolaylı ortaya çıkan zarar, ziyan ve masraflar da dahil, bunlarla sınırlı olmamak üzere herhangi bir zarardan Şirket ve/veya çalışanları sorumlu olamazlar. Bu bilgiler doğrultusunda Şirket&nbsp; bu sitenin içeriğinde yer alan bilgilerden ve g</span><span>örsel malzemeden kaynaklanabilecek hatalardan, maddi veya manevi zararlardan hiç bir şekilde sorumlu değildir.</span></p>
                <p><span><strong>7-Gizlilik ve Kişisel Verilerin Kullanımı</strong></span></p>
                <p><span>7.1 Şirket, … web/mobil sitesine ya da mobil uygulaması üzerinden kullanıcılar tarafından kendisine elektronik ortamda iletilen kişisel bilgileri, Kişisel Verilerin Korunması Kanunu ve dijipol.com internet sitesi arasından ulaşılabilecek Aydınlatma Metni çerçevesinde işlenecek, aktarılacak, s</span><span>öz konusu verilerin kişisel veriler kanunda düzenlenen istinaslar dışında üçüncü kişilere açıklamayacaktır. Bu bilgilere ancak Kullanıcı/</span><span>Üyenin talep ettiği hizmeti yerine getirmek amacıyla ve hizmetin gerektirdiği </span><span>ölçüde Şirket personeli, sigorta şirketlerinin personeli ve iş</span><span>in işleyiş</span><span>i için gerektiği </span><span>ölçüde iş ortakları tarafından ulaşılabilecektir.</span></p>
                <p><span>Kişisel bilgiler, kiş</span><span>i adı-soyadı, T.C Kimlik Numarası, adresi, telefon numarası, cep telefonu, e-posta adresi gibi kullanıcıyı tanımlamaya y</span><span>önelik her türlü diğer bilgiyi içermekte olup, kısaca Gizli Bilgiler olarak anılacaktır.</span></p>
                <p><span>Şirket, işbu Kullanıcı S</span><span>özleşmesinde tanımlı olan haller haricinde kişisel bilgileri herhangi bir Şirket veya üçüncü kişilere açıklamayacaktır. Şirket, kişisel bilgileri kendi bünyesinde, müşteri profili belirlemek, müşteri profiline uygun promosyon ve kampanyalar sunmak ve istatistiksel çalışmalar yapmak ve Aydınlatma Metni</span><span>&apos;nde belirtilen diğer amaçlar için&nbsp; kullanılabilecektir.</span></p>
                <p><span>Şirketin gerekli bilgi güvenliği </span><span>önlemlerini almasına karşın, dijipol.com web/mobil sitesine ya da mobil uygulaması ve sisteme yapılan saldırılar sonucunda gizli bilgilerin zarar g</span><span>örmesi veya üçüncü kişilerin eline geçmesi durumunda, Şirketin herhangi bir sorumluluğu olmayacaktır.</span></p>
                <p><span>7.2 Şirket, kullanıcılara/üyelere ve kullanıcıların/üyelerin dijipol.com web/mobil sitesine ya da mobil uygulamasının kullanımına dair bilgileri, teknik bir iletişim dosyasını kullanarak elde edebilir. Ancak, kullanıcılar dilerlerse teknik iletişim dosyasının gelmemesi veya teknik iletişim dosyası g</span><span>önderildiğinde ikaz verilmesini sağlayacak biçimde, tarayıcı ayarlarını değiştirebilirler.</span></p>
                <p><span>7.3 Şirketin … web/mobil sitesine ya da mobil uygulaması … numaralı numaramız üzerinden hizmet alan kullanıcıları / üyeleri, hizmet alırken ve/veya üye girişi yaparak daha sonra kendi güncelledikleri sabit ve mobil telefon hatları, sabit adresleri, e-posta adresi ve diğer iletişim bilgileri üzerinden, işlem esnasında onay vermiş olmaları şartına bağlı olarak mektup, e-posta, SMS, telefon g</span><span>örüşmesi için arama ve benzeri y</span><span>öntemlerle duyuru, kampanya, </span><span>özel indirim ve diğer pazarlama amaçları ile kullanıcıya ileti g</span><span>önderme hakkı bulunmaktadır.</span></p>
                <p><span>Bu iletiler satın almış olduğunuz ürün veya ürünlerle ilgili bilgiler, ilgileneceğinizi düşündüğümüz diğer ürünler, 3. kurumlarla yürüttüğümüz iş birlikleri doğrultusunda oluşmuş reklamlarını ve benzeri bilgileri içerebilir.</span></p>
                <p><span>Kullanıcı/üyeye g</span><span>önderilecek bütün g</span><span>önderilerin içeriği ve kayıt bilgileri (g</span><span>önderim zamanı, g</span><span>önderim ortamı, g</span><span>önderi adresi/numarası) Şirket tarafından, gerektiğinde ve/veya talep edildiğinde ilgili kurum ve kuruluşlara sunulmak üzere saklanacaktır.</span></p>
                <p><span>7.4 Kullanıcı web sitesi ve/veya telefonda, Şirketin kendisine pazarlama amaçlı iletişim yapması için verdiği onaydan vazgeçmesi durumunda; Şirket g</span><span>önderilen e-postalarda bulunan </span><span>&quot;</span><span>Armor Katılım bültenlerini almak istemiyorsanız tıklayın.&quot; linkine tıklayarak, … adresine e-posta g</span><span>öndererek ya da … numaralı Hattımız</span><span>&apos;dan arayarak e-posta g</span><span>önderim listesinden kolayca çıkabilir, yine&nbsp; … adresine e-posta g</span><span>öndererek ya da … numaralı Hattımız</span><span>&apos;dan arayarak, zaman zaman hizmetlerimiz hakkında bilgi vermek amacı ile g</span><span>önderdiğimiz SMS</span><span>&apos;leri almak ve telefonla aranmak istemediklerini belirtebilirler. </span><span>Üye girişi yapan kişiler, üyelik bilgileri sayfasından bu güncellemeleri kendileri de yapabilirler. Her kullanıcı/üye dilediği zaman iletişim bilgilerini yukarıdaki y</span><span>öntemlerle ileti almak istiyorum statüsüne geri getirebilir. Kullanıcı/ üye bilgileri Şirketin ihtiyaçlar ve/veya teknik gereksinimler dolayısı ile ilerideki herhangi bir zamanda belirleyeceği tarihe kadar saklanacaktır.</span></p>
                <p><span>7.5 Müşteri bilgileri, resmi makamlarca usulü dairesinde bu bilgilerin talep edilmesi halinde ve yürürlükteki emredici mevzuat hükümleri gereğince resmi makamlara açıklama yapmak zorunda olduğu durumlarda resmi makamlara açıklanabilecektir.</span></p>
                <p><span>7.6 Kullanıcı/</span><span>Üye, Şirketin web ve mobil siteleri ve uygulamaları üzerinden gerçekleştireceği her türlü kampanya ve çekilişe katılması durumunda, gerekli bilgilerinin ilgili kişi ve kurumlarla paylaşılmasını kabul, beyan ve taahhüt eder.</span></p>
                <p><span><strong>8-Fikri Mülkiyet Hakları</strong></span></p>
                <p><span>8.1 İşbu web sitesinde ve mobil sitede yer alan unvan, işletme adı</span><span>, marka, patent, logo, tasarım, bilgi ve y</span><span>öntem gibi tescilli veya tescilsiz tüm fikri mülkiyet hakları Şirket veya belirtilen ilgilisine aittir ve ulusal ile uluslararası hukukun koruması altı</span><span>ndadır. İşbu web sitenin ve mobil sitenin ziyaret edilmesi veya bu sitedeki hizmetlerden yararlanılması s</span><span>öz konusu fikri mülkiyet hakları konusunda hiç bir hak vermez. Kullanıcı/</span><span>Üye Şirket sitelerini ziyaret etmek veya kullanmakla anılan fikri mülkiyet haklarını ihlal etmemeyi kabul, beyan ve taahhüt eder.</span></p>
                <p><span>8.2 Sitede yer alan bilgilerin çoğaltılması, başka bir lisana çevrilmesi, saklanması veya işleme tutulması da dahil herhangi bir şekilde kullanılması için Şirketin </span><span>önceden yazılı izni ve onayı gerekir. Bu sebeple işbu web sitesinde ve mobil sitede yer alan bilgiler Şirketin yazılı izni olmadan hiçbir şekilde çoğaltılamaz, yayınlanamaz, kopyalanamaz, sunulamaz ve/veya aktarılamaz. Sitelerin bütünü veya bir kısmı diğer bir web sitesinde izinsiz olarak kullanılamaz. Şirketin yazılı izni olmadıkça bu internet sitesine link verilmesi de yasaktır.</span></p>
                <p><span><strong>9-Sigorta Teminatının Başlaması</strong></span></p>
                <p><span>Sigorta teminatı, sigorta poliçesinin mutabık kalınan koşullarda ilgili sigorta şirketi tarafından düzenlenmesi, peşin yatırılması kararlaştırılan prim miktarının </span><span>ödenmesi ile başlar ve poliçe </span><span>özel ve genel şartlarındaki koşullarla geçerli olur. Poliçe düzenlenmeden </span><span>önce sigorta şirketi tarafından </span><span>&quot;</span><span>couvert&quot; (kuver) verilebilir.</span></p>
                <p><span><strong>10-S</strong></span><span><strong>özleşmenin Süresi ve Feshi</strong></span></p>
                <p><span>10.1 İşbu S</span><span>özleşme </span><span>ÜYE</span><span>&apos;nin üyeliğini iptal etmesi veya Şirket tarafından üyeliğinin iptal edilmesine kadar yürürlükte kalacaktır.</span></p>
                <p><span>10.2&nbsp; Taraflardan her biri işbu S</span><span>özleşme&apos;yi karşı tarafa yapacağı tek taraflı bir bildirimle her zaman feshedebilir.</span></p>
                <p><span><strong>11-İhtilafların Çözümü</strong></span></p>
                <p><span>Kullanıcıların Şirketin herhangi bir iletişim kanalından alacağın hizmetler nedeniyle bir ihtilaf doğ</span><span>ması durumunda Türk hukuku uygulanacak ve İstanbul (merkez) mahkemeleri ve icra daireleri yetkili olacaktır.</span></p>
                <p><span><strong>12-Yürürlük</strong></span></p>
                <p><span>İşbu S</span><span>özleşme kullanıcının/üyenin s</span><span>özleşme hükümlerini okuduğunu ve kabul ettiğini beyan etmesi ile akdedilmiş ve yürürlüğe girmiştir.</span></p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
} 